version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: cue-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cue_admin
      POSTGRES_PASSWORD: cue_secure_pass
      POSTGRES_DB: cue_judge
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: